// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: services/shutdown/shutdown.proto

package shutdown

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Shutdown_InitiateSystemShutdown_FullMethodName = "/services.shutdown.Shutdown/InitiateSystemShutdown"
	Shutdown_AbortSystemShutdown_FullMethodName    = "/services.shutdown.Shutdown/AbortSystemShutdown"
)

// ShutdownClient is the client API for Shutdown service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShutdownClient interface {
	InitiateSystemShutdown(ctx context.Context, in *InitiateSystemShutdownRequest, opts ...grpc.CallOption) (*InitiateSystemShutdownResponse, error)
	AbortSystemShutdown(ctx context.Context, in *AbortSystemShutdownRequest, opts ...grpc.CallOption) (*AbortSystemShutdownResponse, error)
}

type shutdownClient struct {
	cc grpc.ClientConnInterface
}

func NewShutdownClient(cc grpc.ClientConnInterface) ShutdownClient {
	return &shutdownClient{cc}
}

func (c *shutdownClient) InitiateSystemShutdown(ctx context.Context, in *InitiateSystemShutdownRequest, opts ...grpc.CallOption) (*InitiateSystemShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateSystemShutdownResponse)
	err := c.cc.Invoke(ctx, Shutdown_InitiateSystemShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shutdownClient) AbortSystemShutdown(ctx context.Context, in *AbortSystemShutdownRequest, opts ...grpc.CallOption) (*AbortSystemShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortSystemShutdownResponse)
	err := c.cc.Invoke(ctx, Shutdown_AbortSystemShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShutdownServer is the server API for Shutdown service.
// All implementations must embed UnimplementedShutdownServer
// for forward compatibility
type ShutdownServer interface {
	InitiateSystemShutdown(context.Context, *InitiateSystemShutdownRequest) (*InitiateSystemShutdownResponse, error)
	AbortSystemShutdown(context.Context, *AbortSystemShutdownRequest) (*AbortSystemShutdownResponse, error)
	mustEmbedUnimplementedShutdownServer()
}

// UnimplementedShutdownServer must be embedded to have forward compatible implementations.
type UnimplementedShutdownServer struct {
}

func (UnimplementedShutdownServer) InitiateSystemShutdown(context.Context, *InitiateSystemShutdownRequest) (*InitiateSystemShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateSystemShutdown not implemented")
}
func (UnimplementedShutdownServer) AbortSystemShutdown(context.Context, *AbortSystemShutdownRequest) (*AbortSystemShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortSystemShutdown not implemented")
}
func (UnimplementedShutdownServer) mustEmbedUnimplementedShutdownServer() {}

// UnsafeShutdownServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShutdownServer will
// result in compilation errors.
type UnsafeShutdownServer interface {
	mustEmbedUnimplementedShutdownServer()
}

func RegisterShutdownServer(s grpc.ServiceRegistrar, srv ShutdownServer) {
	s.RegisterService(&Shutdown_ServiceDesc, srv)
}

func _Shutdown_InitiateSystemShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateSystemShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShutdownServer).InitiateSystemShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shutdown_InitiateSystemShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShutdownServer).InitiateSystemShutdown(ctx, req.(*InitiateSystemShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shutdown_AbortSystemShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortSystemShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShutdownServer).AbortSystemShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shutdown_AbortSystemShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShutdownServer).AbortSystemShutdown(ctx, req.(*AbortSystemShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Shutdown_ServiceDesc is the grpc.ServiceDesc for Shutdown service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shutdown_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.shutdown.Shutdown",
	HandlerType: (*ShutdownServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateSystemShutdown",
			Handler:    _Shutdown_InitiateSystemShutdown_Handler,
		},
		{
			MethodName: "AbortSystemShutdown",
			Handler:    _Shutdown_AbortSystemShutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/shutdown/shutdown.proto",
}
