// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: services/netmgmt/netmgmt.proto

package netmgmt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Netmgmt_AddUser_FullMethodName                  = "/services.netmgmt.Netmgmt/AddUser"
	Netmgmt_DeleteUser_FullMethodName               = "/services.netmgmt.Netmgmt/DeleteUser"
	Netmgmt_GetUsers_FullMethodName                 = "/services.netmgmt.Netmgmt/GetUsers"
	Netmgmt_GetUser_FullMethodName                  = "/services.netmgmt.Netmgmt/GetUser"
	Netmgmt_GetMyUser_FullMethodName                = "/services.netmgmt.Netmgmt/GetMyUser"
	Netmgmt_GetUserLocalGroups_FullMethodName       = "/services.netmgmt.Netmgmt/GetUserLocalGroups"
	Netmgmt_GetMyUserLocalGroups_FullMethodName     = "/services.netmgmt.Netmgmt/GetMyUserLocalGroups"
	Netmgmt_ChangeUserPassword_FullMethodName       = "/services.netmgmt.Netmgmt/ChangeUserPassword"
	Netmgmt_ChangeMyUserPassword_FullMethodName     = "/services.netmgmt.Netmgmt/ChangeMyUserPassword"
	Netmgmt_EnableUser_FullMethodName               = "/services.netmgmt.Netmgmt/EnableUser"
	Netmgmt_DisableUser_FullMethodName              = "/services.netmgmt.Netmgmt/DisableUser"
	Netmgmt_AddUserToLocalGroup_FullMethodName      = "/services.netmgmt.Netmgmt/AddUserToLocalGroup"
	Netmgmt_RemoveUserFromLocalGroup_FullMethodName = "/services.netmgmt.Netmgmt/RemoveUserFromLocalGroup"
	Netmgmt_GetLocalGroups_FullMethodName           = "/services.netmgmt.Netmgmt/GetLocalGroups"
	Netmgmt_GetUsersInLocalGroup_FullMethodName     = "/services.netmgmt.Netmgmt/GetUsersInLocalGroup"
)

// NetmgmtClient is the client API for Netmgmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetmgmtClient interface {
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetMyUser(ctx context.Context, in *GetMyUserRequest, opts ...grpc.CallOption) (*GetMyUserResponse, error)
	GetUserLocalGroups(ctx context.Context, in *GetUserLocalGroupsRequest, opts ...grpc.CallOption) (*GetUserLocalGroupsResponse, error)
	GetMyUserLocalGroups(ctx context.Context, in *GetMyUserLocalGroupsRequest, opts ...grpc.CallOption) (*GetMyUserLocalGroupsResponse, error)
	ChangeUserPassword(ctx context.Context, in *ChangeUserPasswordRequest, opts ...grpc.CallOption) (*ChangeUserPasswordResponse, error)
	ChangeMyUserPassword(ctx context.Context, in *ChangeMyUserPasswordRequest, opts ...grpc.CallOption) (*ChangeMyUserPasswordResponse, error)
	EnableUser(ctx context.Context, in *EnableUserRequest, opts ...grpc.CallOption) (*EnableUserResponse, error)
	DisableUser(ctx context.Context, in *DisableUserRequest, opts ...grpc.CallOption) (*DisableUserResponse, error)
	AddUserToLocalGroup(ctx context.Context, in *AddUserToLocalGroupRequest, opts ...grpc.CallOption) (*AddUserToLocalGroupResponse, error)
	RemoveUserFromLocalGroup(ctx context.Context, in *RemoveUserFromLocalGroupRequest, opts ...grpc.CallOption) (*RemoveUserFromLocalGroupResponse, error)
	GetLocalGroups(ctx context.Context, in *GetLocalGroupsRequest, opts ...grpc.CallOption) (*GetLocalGroupsResponse, error)
	GetUsersInLocalGroup(ctx context.Context, in *GetUsersInLocalGroupRequest, opts ...grpc.CallOption) (*GetUsersInLocalGroupResponse, error)
}

type netmgmtClient struct {
	cc grpc.ClientConnInterface
}

func NewNetmgmtClient(cc grpc.ClientConnInterface) NetmgmtClient {
	return &netmgmtClient{cc}
}

func (c *netmgmtClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, Netmgmt_AddUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, Netmgmt_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, Netmgmt_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, Netmgmt_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) GetMyUser(ctx context.Context, in *GetMyUserRequest, opts ...grpc.CallOption) (*GetMyUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyUserResponse)
	err := c.cc.Invoke(ctx, Netmgmt_GetMyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) GetUserLocalGroups(ctx context.Context, in *GetUserLocalGroupsRequest, opts ...grpc.CallOption) (*GetUserLocalGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLocalGroupsResponse)
	err := c.cc.Invoke(ctx, Netmgmt_GetUserLocalGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) GetMyUserLocalGroups(ctx context.Context, in *GetMyUserLocalGroupsRequest, opts ...grpc.CallOption) (*GetMyUserLocalGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyUserLocalGroupsResponse)
	err := c.cc.Invoke(ctx, Netmgmt_GetMyUserLocalGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) ChangeUserPassword(ctx context.Context, in *ChangeUserPasswordRequest, opts ...grpc.CallOption) (*ChangeUserPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeUserPasswordResponse)
	err := c.cc.Invoke(ctx, Netmgmt_ChangeUserPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) ChangeMyUserPassword(ctx context.Context, in *ChangeMyUserPasswordRequest, opts ...grpc.CallOption) (*ChangeMyUserPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeMyUserPasswordResponse)
	err := c.cc.Invoke(ctx, Netmgmt_ChangeMyUserPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) EnableUser(ctx context.Context, in *EnableUserRequest, opts ...grpc.CallOption) (*EnableUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableUserResponse)
	err := c.cc.Invoke(ctx, Netmgmt_EnableUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) DisableUser(ctx context.Context, in *DisableUserRequest, opts ...grpc.CallOption) (*DisableUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableUserResponse)
	err := c.cc.Invoke(ctx, Netmgmt_DisableUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) AddUserToLocalGroup(ctx context.Context, in *AddUserToLocalGroupRequest, opts ...grpc.CallOption) (*AddUserToLocalGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserToLocalGroupResponse)
	err := c.cc.Invoke(ctx, Netmgmt_AddUserToLocalGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) RemoveUserFromLocalGroup(ctx context.Context, in *RemoveUserFromLocalGroupRequest, opts ...grpc.CallOption) (*RemoveUserFromLocalGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserFromLocalGroupResponse)
	err := c.cc.Invoke(ctx, Netmgmt_RemoveUserFromLocalGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) GetLocalGroups(ctx context.Context, in *GetLocalGroupsRequest, opts ...grpc.CallOption) (*GetLocalGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocalGroupsResponse)
	err := c.cc.Invoke(ctx, Netmgmt_GetLocalGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) GetUsersInLocalGroup(ctx context.Context, in *GetUsersInLocalGroupRequest, opts ...grpc.CallOption) (*GetUsersInLocalGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersInLocalGroupResponse)
	err := c.cc.Invoke(ctx, Netmgmt_GetUsersInLocalGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetmgmtServer is the server API for Netmgmt service.
// All implementations must embed UnimplementedNetmgmtServer
// for forward compatibility
type NetmgmtServer interface {
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetMyUser(context.Context, *GetMyUserRequest) (*GetMyUserResponse, error)
	GetUserLocalGroups(context.Context, *GetUserLocalGroupsRequest) (*GetUserLocalGroupsResponse, error)
	GetMyUserLocalGroups(context.Context, *GetMyUserLocalGroupsRequest) (*GetMyUserLocalGroupsResponse, error)
	ChangeUserPassword(context.Context, *ChangeUserPasswordRequest) (*ChangeUserPasswordResponse, error)
	ChangeMyUserPassword(context.Context, *ChangeMyUserPasswordRequest) (*ChangeMyUserPasswordResponse, error)
	EnableUser(context.Context, *EnableUserRequest) (*EnableUserResponse, error)
	DisableUser(context.Context, *DisableUserRequest) (*DisableUserResponse, error)
	AddUserToLocalGroup(context.Context, *AddUserToLocalGroupRequest) (*AddUserToLocalGroupResponse, error)
	RemoveUserFromLocalGroup(context.Context, *RemoveUserFromLocalGroupRequest) (*RemoveUserFromLocalGroupResponse, error)
	GetLocalGroups(context.Context, *GetLocalGroupsRequest) (*GetLocalGroupsResponse, error)
	GetUsersInLocalGroup(context.Context, *GetUsersInLocalGroupRequest) (*GetUsersInLocalGroupResponse, error)
	mustEmbedUnimplementedNetmgmtServer()
}

// UnimplementedNetmgmtServer must be embedded to have forward compatible implementations.
type UnimplementedNetmgmtServer struct {
}

func (UnimplementedNetmgmtServer) AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedNetmgmtServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedNetmgmtServer) GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedNetmgmtServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedNetmgmtServer) GetMyUser(context.Context, *GetMyUserRequest) (*GetMyUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyUser not implemented")
}
func (UnimplementedNetmgmtServer) GetUserLocalGroups(context.Context, *GetUserLocalGroupsRequest) (*GetUserLocalGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLocalGroups not implemented")
}
func (UnimplementedNetmgmtServer) GetMyUserLocalGroups(context.Context, *GetMyUserLocalGroupsRequest) (*GetMyUserLocalGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyUserLocalGroups not implemented")
}
func (UnimplementedNetmgmtServer) ChangeUserPassword(context.Context, *ChangeUserPasswordRequest) (*ChangeUserPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeUserPassword not implemented")
}
func (UnimplementedNetmgmtServer) ChangeMyUserPassword(context.Context, *ChangeMyUserPasswordRequest) (*ChangeMyUserPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeMyUserPassword not implemented")
}
func (UnimplementedNetmgmtServer) EnableUser(context.Context, *EnableUserRequest) (*EnableUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableUser not implemented")
}
func (UnimplementedNetmgmtServer) DisableUser(context.Context, *DisableUserRequest) (*DisableUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableUser not implemented")
}
func (UnimplementedNetmgmtServer) AddUserToLocalGroup(context.Context, *AddUserToLocalGroupRequest) (*AddUserToLocalGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserToLocalGroup not implemented")
}
func (UnimplementedNetmgmtServer) RemoveUserFromLocalGroup(context.Context, *RemoveUserFromLocalGroupRequest) (*RemoveUserFromLocalGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserFromLocalGroup not implemented")
}
func (UnimplementedNetmgmtServer) GetLocalGroups(context.Context, *GetLocalGroupsRequest) (*GetLocalGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocalGroups not implemented")
}
func (UnimplementedNetmgmtServer) GetUsersInLocalGroup(context.Context, *GetUsersInLocalGroupRequest) (*GetUsersInLocalGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersInLocalGroup not implemented")
}
func (UnimplementedNetmgmtServer) mustEmbedUnimplementedNetmgmtServer() {}

// UnsafeNetmgmtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetmgmtServer will
// result in compilation errors.
type UnsafeNetmgmtServer interface {
	mustEmbedUnimplementedNetmgmtServer()
}

func RegisterNetmgmtServer(s grpc.ServiceRegistrar, srv NetmgmtServer) {
	s.RegisterService(&Netmgmt_ServiceDesc, srv)
}

func _Netmgmt_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_GetMyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).GetMyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_GetMyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).GetMyUser(ctx, req.(*GetMyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_GetUserLocalGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLocalGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).GetUserLocalGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_GetUserLocalGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).GetUserLocalGroups(ctx, req.(*GetUserLocalGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_GetMyUserLocalGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyUserLocalGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).GetMyUserLocalGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_GetMyUserLocalGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).GetMyUserLocalGroups(ctx, req.(*GetMyUserLocalGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_ChangeUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).ChangeUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_ChangeUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).ChangeUserPassword(ctx, req.(*ChangeUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_ChangeMyUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMyUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).ChangeMyUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_ChangeMyUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).ChangeMyUserPassword(ctx, req.(*ChangeMyUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_EnableUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).EnableUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_EnableUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).EnableUser(ctx, req.(*EnableUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_DisableUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).DisableUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_DisableUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).DisableUser(ctx, req.(*DisableUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_AddUserToLocalGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserToLocalGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).AddUserToLocalGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_AddUserToLocalGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).AddUserToLocalGroup(ctx, req.(*AddUserToLocalGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_RemoveUserFromLocalGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromLocalGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).RemoveUserFromLocalGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_RemoveUserFromLocalGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).RemoveUserFromLocalGroup(ctx, req.(*RemoveUserFromLocalGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_GetLocalGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).GetLocalGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_GetLocalGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).GetLocalGroups(ctx, req.(*GetLocalGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_GetUsersInLocalGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersInLocalGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).GetUsersInLocalGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netmgmt_GetUsersInLocalGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).GetUsersInLocalGroup(ctx, req.(*GetUsersInLocalGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Netmgmt_ServiceDesc is the grpc.ServiceDesc for Netmgmt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Netmgmt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.netmgmt.Netmgmt",
	HandlerType: (*NetmgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _Netmgmt_AddUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Netmgmt_DeleteUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _Netmgmt_GetUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Netmgmt_GetUser_Handler,
		},
		{
			MethodName: "GetMyUser",
			Handler:    _Netmgmt_GetMyUser_Handler,
		},
		{
			MethodName: "GetUserLocalGroups",
			Handler:    _Netmgmt_GetUserLocalGroups_Handler,
		},
		{
			MethodName: "GetMyUserLocalGroups",
			Handler:    _Netmgmt_GetMyUserLocalGroups_Handler,
		},
		{
			MethodName: "ChangeUserPassword",
			Handler:    _Netmgmt_ChangeUserPassword_Handler,
		},
		{
			MethodName: "ChangeMyUserPassword",
			Handler:    _Netmgmt_ChangeMyUserPassword_Handler,
		},
		{
			MethodName: "EnableUser",
			Handler:    _Netmgmt_EnableUser_Handler,
		},
		{
			MethodName: "DisableUser",
			Handler:    _Netmgmt_DisableUser_Handler,
		},
		{
			MethodName: "AddUserToLocalGroup",
			Handler:    _Netmgmt_AddUserToLocalGroup_Handler,
		},
		{
			MethodName: "RemoveUserFromLocalGroup",
			Handler:    _Netmgmt_RemoveUserFromLocalGroup_Handler,
		},
		{
			MethodName: "GetLocalGroups",
			Handler:    _Netmgmt_GetLocalGroups_Handler,
		},
		{
			MethodName: "GetUsersInLocalGroup",
			Handler:    _Netmgmt_GetUsersInLocalGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/netmgmt/netmgmt.proto",
}
